AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketName:
    Type: String
  UserArn:
    Type: String
    
    
Resources:

  IncomingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      

  IncomingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref IncomingBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:Get*'
              - 's3:Put*'
              - 's3:List*'
            Effect: Allow
            Principal:
              'AWS': !Ref UserArn
            Resource: 
              - !Sub '${IncomingBucket.Arn}/*'
              - !Sub '${IncomingBucket.Arn}'

          - Action:
              - 's3:Delete*'
            Effect: Deny
            Principal:
              'AWS': !Ref UserArn
            Resource:
              - !Sub '${IncomingBucket.Arn}/*'
              - !Sub '${IncomingBucket.Arn}'
