AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: pmr-dice-use1


Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-047a51fa27710816e
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          GroupSet:
            sg-01389c46cccd1c62c
          SubnetId: subnet-05e98c276c30b74a7
      Tags:
        Key: Name
          Value: web server

      # Metadata:
      #   AWS::CloudFormation::Init:
      #     config:
      #       packages:
      #         :
      #       groups:
      #         :
      #       users:
      #         :
      #       sources:
      #         :
      #       files:
      #         :
      #       commands:
      #         :
      #       services:
      #         :
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            # Install the files and packages from the metadata
            /opt/aws/bin/cfn-init -v
                     --stack ${AWS::StackName}
                     --resource WebServerInstance
                     --configsets InstallAndRun
                     --region ${AWS::Region}
